spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #    password: 135799
    password: root
    # mysql6中serverTimezone需要自己手动设定，这里设定的是CTT中国台湾，可以避免时差
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    #Druid连接池配置相关
    druid:
      # 初始大小，最大，最小
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

  # redis
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 2
        max-idle: 20
        min-idle: 1
  # 热部署
  #  devtools:
  #    remote:
  #      restart:
  #        enabled: true
  #    restart:
  #      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  # 吐血 加了LEGACYHTML5mode之后静态资源一直获取不到
  #  thymeleaf:
  #    cache: false
  #    mode: LEGACYHTML5
  #  mvc:
  #    static-path-pattern: /static/**,/templates/**
#  classpath:/resources/,
  resources:
    static-locations: classpath:/,classpath:/templates/


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
# 打印mysql
logging:
  level:
    com.example.blog.dao: debug
server:
  port: 8888


